#!/bin/bash
# bootable system full backup

# vim : filetype=sh

# Backup type.
type="bootable"

# Backup destination
backdest="/opt/backup/${type}"

# Labels for backup name
#PC=${HOSTNAME}
distro="$(uname -r)"
date="$(date "+%F")"
backupfile="${backdest}/full-backup/${distro}-${type}-${date}.tar.xz"

# Exclude file location
prog=${0##*/} # Program name from filename
excdir="${backdest}/etc/"
exclude_file="${excdir}/${type}-exclude"

# Check if chrooted prompt.
echo -n "First chroot from a LiveCD.  Are you ready to backup? (y/n): "
read executeback

# Check if exclude file exists
if [ ! -f "${exclude_file}" ]; then
  echo -n "No exclude file exists, continue? (y/n): "
  read continue
  if [ "${continue}" == "n" ]; then exit; fi
fi

if [ "${executeback}" = "y" ]; then
  # -p and --xattrs store all permissions and extended attributes. 
  # Without both of these, many programs will stop working!
  # It is safe to remove the verbose (-v) flag. If you are using a 
  # slow terminal, this can greatly speed up the backup process.
  tar --exclude-from="${exclude_file}" --xattrs -cJpvf "${backupfile}" /
fi
